### ISSUE TITLE
Both "color" and "Colour" shows incorrect spelling(Red Squiggle line)

### ISSUE THREAD

**Issue by shaileshparmar1997** [DevExpress-Examples/how-to-check-spelling-within-the-rich-edit-control-e2640#4]
i have downloaded code and running same code. In, the editor, I write  "Color" (which is US English ) and "Colour" (which is British English) but in both cases I see error red Squiggle line. I have Attach Screen Shot herewith 
![Error](https://user-images.githubusercontent.com/41322461/103767125-15497300-5046-11eb-9215-ce1e23eb21a9.PNG)
   In project US English dictionary has already been added so, "Color" Should not show error Squiggle line. Can you please check and revert back. what could be issue

**Comment by YuliaDX** [comment]
Hello,

I see that you asked this question in our [Support Center](https://supportcenter.devexpress.com/ticket/list). We will contact you there.
